### ISSUE TITLE
Multi VM on latest main not working

### ISSUE THREAD

**Issue by krotz-dieter** [Siemens-Healthineers/K2s#119]
**Describe the bug**
Multi VM install breaks with an error downloading kubectl

**To Reproduce**
call `k2s install multivm ...`

**Expected behavior**
Error during download of kubectl. Attachment shows error.

**Screenshots**
![Error-MultiVM](https://github.com/Siemens-Healthineers/K2s/assets/47243396/f7fca7e9-7efe-408a-a95b-0b54d379ab0b)

**Comment by krotz-dieter** [comment]
Also Linux Only Setup breaks because of same error:
I0209 08:36:05.048271    4640 main.go:299] â³ [08:36:05] Download 'https://dl.k8s.io/release/v1.25.13/bin/windows/amd64/kubectl.exe' failed
I0209 08:36:05.187834    4640 main.go:299] â³ [33mDownloadFile : Download 'https://dl.k8s.io/release/v1.25.13/bin/windows/amd64/kubectl.exe' failed[0m
I0209 08:36:05.188104    4640 main.go:299] â³ [33mAt C:\k2s\smallsetup\multivm\Install_MultiVMK8sSetup.ps1:353 char:9[0m
I0209 08:36:05.188201    4640 main.go:299] â³ [33m+         DownloadFile "&$global:KubectlExe" https://dl.k8s.io/release/ ...[0m
I0209 08:36:05.188382    4640 main.go:299] â³ [33m+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m
I0209 08:36:05.188382    4640 main.go:299] â³ [33m    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException[0m
I0209 08:36:05.188382    4640 main.go:299] â³ [33m    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DownloadFile[0m
I0209 08:36:05.188707    4640 main.go:299] â³ [33m [0m
I0209 08:36:05.266411    4640 main.go:314] E0209 08:36:05.263859    3528 psexecutor.go:441] DownloadFile : Download 'https://dl.k8s.io/release/v1.25.13/bin/windows/amd64/kubectl.exe' failed
I0209 08:36:05.266411    4640 main.go:314] At C:\k2s\smallsetup\multivm\Install_MultiVMK8sSetup.ps1:353 char:9
I0209 08:36:05.266411    4640 main.go:314] +         DownloadFile "&$global:KubectlExe" https://dl.k8s.io/release/ ...
I0209 08:36:05.266411    4640 main.go:314] +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I0209 08:36:05.266411    4640 main.go:314]     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
I0209 08:36:05.266411    4640 main.go:314]     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DownloadFile
I0209 08:36:05.266411    4640 main.go:314]  
I0209 08:36:05.269289    4640 main.go:299] [30;101m[30;101m  ERROR  [0m[0m [91m[91mcommand execution failed, see log output above. Error: exit code 1[0m[0m

**Comment by gabriel-rosso** [comment]
Related to issue #176. Solved with solution provided for it.
