### ISSUE TITLE
Timestamps are missing when enabling/disabling/importing/exporting addons

### ISSUE THREAD

**Issue by achimkist** [Siemens-Healthineers/K2s#130]
![image](https://github.com/Siemens-Healthineers/K2s/assets/155652202/8a7dc542-da16-41b0-9817-6b211be1f4d9)

**Comment by achimkist** [comment]
not only related to gpu-node addon, also during addons import and export

**Comment by mahenarayan** [comment]
**Details:**

This is due missing usage of Invoke-ExecScript.ps1. This is entry point script which dictates logging when there is no EncodeStructuredOutput is necessary.

Invoke-ExecScript.ps1 should be used as entry point for all the scripts except in the case on EncodeStructuredOutput (e.g Status, Enabled addons)

**Comment by mahenarayan** [comment]
Additionally, it makes sense to include module::functionname information in the log file, this is not relevant for user in the console.
E.g. cli-messages.module.psm1::Send-ToCli information in the log file

```
⏳ [08:43:45] [cli-messages.module.psm1::Send-ToCli] Converting message of type 'CmdResult' to JSON..
⏳ [08:43:45] [cli-messages.module.psm1::Send-ToCli] message converted
⏳ [08:43:45] [cli-messages.module.psm1::Send-ToCli] JSON compressed
⏳ [08:43:45] [cli-messages.module.psm1::Send-ToCli] JSON base64 encoded
⏳ [08:43:45] [cli-messages.module.psm1::Send-ToCli] message sent via CLI
```
 For the user:
```
⏳ [08:43:45] Converting message of type 'CmdResult' to JSON..
⏳ [08:43:45] message converted
⏳ [08:43:45] JSON compressed
⏳ [08:43:45] JSON base64 encoded
⏳ [08:43:45] message sent via CLI
```

This can be achieved using Invoke-ExecScript.ps1.

**Comment by achimkist** [comment]
CI pipeline broken

**Comment by achimkist** [comment]
  k2s system ssh m -- echo test
⏳ Write-Log : [10:02:05] C:\k2s\smallsetup\helpers\sshm.ps1 : A positional parameter cannot be found that accepts argument 'echo'.  At line:1 char:1  + &'C:\k2s\smallsetup\helpers\sshm.ps1' -EncodeStructuredOutput -Messag ...  +
⏳ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      + CategoryInfo          : InvalidArgument: (:) [sshm.ps1], ParameterBindingException      + FullyQualifiedErrorId : PositionalParameterNotFound,sshm.ps1
⏳ At C:\k2s\lib\scripts\k2s\base\Invoke-ExecScript.ps1:44 char:9
⏳ +         Write-Log $($_ | Out-String) -Error
⏳ +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
⏳     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
⏳     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log
⏳
time=2024-04-10T10:02:05.421+02:00 level=ERROR source=common.go:174 msg="Flushing error lines" count=8 lines="[Write-Log : [10:02:05] C:\\k2s\\smallsetup\\helpers\\sshm.ps1 : A positional parameter cannot be found that accepts argument 'echo'.  At line:1 char:1  + &'C:\\k2s\\smallsetup\\helpers\\sshm.ps1' -EncodeStructuredOutput -Messag ...  +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      + CategoryInfo          : InvalidArgument: (:) [sshm.ps1], ParameterBindingException      + FullyQualifiedErrorId : PositionalParameterNotFound,sshm.ps1      At C:\\k2s\\lib\\scripts\\k2s\\base\\Invoke-ExecScript.ps1:44 char:9 +         Write-Log $($_ | Out-String) -Error +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log  ]"
  ERROR   unexpected number of messages. Expected 1, but got 0
