### ISSUE TITLE
Addon exthttpaccess is still available after k2s uninstall

### ISSUE THREAD

**Issue by achimkist** [Siemens-Healthineers/K2s#164]
**Describe the bug**
Addon exthttpaccess is still available after k2s uninstall

**To Reproduce**
1. k2s install
2. k2 addons enable exthttpaccess
3. k2s uninstall

**Expected behavior**
After k2s uninstall nssm service "ExtHttpAccess-nginx" should be removed

**Additional context**
Solution: add "AfterUninstall" hook and stop and remove nssm service ""ExtHttpAccess-nginx""

**Comment by mahenarayan** [comment]
Also, please rename nssm service name from `ExtHttpAccess-nginx` to `nginx-ext`
