### ISSUE TITLE
Provide common proxy handling support for windows node

### ISSUE THREAD

**Issue by mahenarayan** [Siemens-Healthineers/K2s#170]
**Is your feature request related to a problem? Please describe.**

Applies only to the Proxy scenario.
As a k2s user, I encounter difficulty in configuring proxy and no-proxy variables for Windows node components such as containerd, httpproxy, and docker. This challenge arises from the necessity of possessing intricate knowledge about each component. Moreover, any modifications to these components in the future could lead to deviations in proxy handling, consequently disrupting proxy use cases.

**Describe the solution you'd like**

To enhance user experience and streamline proxy configuration, I propose the implementation of a centralized proxy configuration mechanism. This mechanism involves placing proxy and no-proxy variables under a designated file location, specifically at `c:\etc\k2s\proxy.conf`

The content of proxy.conf would be structured as follows:
```
http_proxy=http://10.11.12.13:80/
https_proxy=http://10.11.12.13:80/
no_proxy=.svc,.cluster.local,kubernetes.default.svc,127.0.0.1
```
This configuration file will be automatically recognized during the startup of the k2s cluster. The specified proxy settings will then be applied to Windows node components. This user-friendly approach not only simplifies the proxy configuration process but also ensures consistency and adaptability, mitigating the impact of future modifications to individual components on proxy functionality.

**Describe alternatives you've considered**

An alternative approach that has been considered involves the implementation of PowerShell hooks for initiating and installing proxy configurations. However, this method requires in-depth knowledge about the internal components of k2s, making it potentially challenging for users without a comprehensive understanding of the system.

**Comment by achimkist** [comment]
Discussion 6/13/2024:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- keep **proxy** parameter for install command (override windows system proxy settings in that case)
- add **noproxy** paramater for install command 
- store provided proxy conf e.g. in setup.json
-  route all traeffic from windows components through local httpproxy service and then forward to real proxy
- remove proxy parameter from all other commands e.g. k2s addons enable, export
- add **k2s system proxy** command to set proxy parameters and configure httpproxy service
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
