### ISSUE TITLE
Argo test run addonsexportimport is broken

### ISSUE THREAD

**Issue by krotz-dieter** [Siemens-Healthineers/K2s#172]
**Describe the bug**
Argo test run addonsexportimport is broken: test-k2s-addonsexportimport-online-windows10

**Additional context**
I0216 07:42:47.310451    7060 main.go:1131]   [FAILED] in [BeforeSuite] - C:/k2s/test/framework/suite.go:235 @ 02/16/24 07:42:47.308
I0216 07:42:47.310536    7060 main.go:1131] [BeforeSuite] [FAILED] [2.031 seconds]
I0216 07:42:47.310594    7060 main.go:1131] [BeforeSuite] 
I0216 07:42:47.310594    7060 main.go:1131] C:/k2s/test/e2e/addons/export_import_test.go:44
I0216 07:42:47.310726    7060 main.go:1131] 
I0216 07:42:47.310726    7060 main.go:1131]   [FAILED] Expected
I0216 07:42:47.310795    7060 main.go:1131]       <*errors.errorString | 0xc000452670>: 
I0216 07:42:47.310861    7060 main.go:1131]       could not load enabled addons: open C:\k2s\test\e2e\addons\cfg\config.json: The system cannot find the path specified.
I0216 07:42:47.310954    7060 main.go:1131]       {
I0216 07:42:47.311024    7060 main.go:1131]           s: "could not load enabled addons: open C:\\k2s\\test\\e2e\\addons\\cfg\\config.json: The system cannot find the path specified.",
I0216 07:42:47.311090    7060 main.go:1131]       }
I0216 07:42:47.311090    7060 main.go:1131]   to be nil
I0216 07:42:47.311221    7060 main.go:1131]   In [BeforeSuite] at: C:/k2s/test/framework/suite.go:235 @ 02/16/24 07:42:47.308
I0216 07:42:47.311292    7060 main.go:1131] ------------------------------
I0216 07:42:47.311292    7060 main.go:1131] [AfterSuite] 
I0216 07:42:47.311434    7060 main.go:1131] C:/k2s/test/e2e/addons/export_import_test.go:59
I0216 07:42:47.311434    7060 main.go:1131]   Waiting for all started processes to die..
I0216 07:42:47.311690    7060 main.go:1131]   All processes exited
I0216 07:42:47.311828    7060 main.go:1131] [AfterSuite] PASSED [0.000 seconds]
I0216 07:42:47.311828    7060 main.go:1131] ------------------------------
I0216 07:42:47.311935    7060 main.go:1131] [ReportAfterSuite] Autogenerated ReportAfterSuite for --junit-report
I0216 07:42:47.311935    7060 main.go:1131] autogenerated by Ginkgo
I0216 07:42:47.312046    7060 main.go:1131] [ReportAfterSuite] PASSED [0.002 seconds]

**Comment by krotz-dieter** [comment]
Also addons tests have the same failure as root cause.

**Comment by achimkist** [comment]
fixed with PR #181
