### ISSUE TITLE
Update Kubernetes version

### ISSUE THREAD

**Issue by mahenarayan** [Siemens-Healthineers/K2s#173]
**Is your feature request related to a problem? Please describe.**
Currently, k2s uses v1.25.13 as Kubernetes version, which is out of support. Hence needs an upgrade to the latest one.

**Describe the solution you'd like**
Use the latest Kubernetes version and evaluate all uses cases. 

**Additional context**
![image](https://github.com/Siemens-Healthineers/K2s/assets/154434373/8f88d8d1-c1b2-4dcc-bef7-ca759cd8de2b)

**Comment by krotz-dieter** [comment]
Finalized by bringing K8s 1.29.5
