### ISSUE TITLE
Argo test runs on windows 11, windows 22 are broken

### ISSUE THREAD

**Issue by krotz-dieter** [Siemens-Healthineers/K2s#175]
**Describe the bug**
Argo test runs on windows 11, windows 22 are broken

**Additional context**
Summarizing 1 Failure:
I0216 03:23:55.357512    3772 main.go:1131] ------------------------------
I0216 03:23:55.357512    3772 main.go:1131] status default output prints setup
I0216 03:23:55.357512    3772 main.go:1131] C:/k2s/test/e2e/cli/cmd/status/setuprequired/systemrunning/status_system-running_test.go:58
I0216 03:23:55.357512    3772 main.go:1131] + [0.000 seconds]
I0216 03:23:55.357512    3772 main.go:1131] ------------------------------
I0216 03:23:55.357857    3772 main.go:1131] status default output prints version
I0216 03:23:55.357857    3772 main.go:1131] C:/k2s/test/e2e/cli/cmd/status/setuprequired/systemrunning/status_system-running_test.go:62
I0216 03:23:55.357857    3772 main.go:1131] + [0.000 seconds]
I0216 03:23:55.358061    3772 main.go:1131] ------------------------------
I0216 03:23:55.358061    3772 main.go:1131] status default output prints addons
I0216 03:23:55.358191    3772 main.go:1131] C:/k2s/test/e2e/cli/cmd/status/setuprequired/systemrunning/status_system-running_test.go:66
I0216 03:23:55.360212    3772 main.go:1131]   [FAILED] in [It] - C:/k2s/test/e2e/cli/cmd/status/setuprequired/common/common.go:18 @ 02/16/24 03:23:55.359
I0216 03:23:55.360212    3772 main.go:1131] + [FAILED] [0.003 seconds]
I0216 03:23:55.360394    3772 main.go:1131] status default output [It] prints addons
I0216 03:23:55.360394    3772 main.go:1131] C:/k2s/test/e2e/cli/cmd/status/setuprequired/systemrunning/status_system-running_test.go:66
I0216 03:23:55.360394    3772 main.go:1131] 
I0216 03:23:55.360517    3772 main.go:1131]   [FAILED] Expected
I0216 03:23:55.360517    3772 main.go:1131]       <string>: K2s SYSTEM STATUS
I0216 03:23:55.360517    3772 main.go:1131]       
...
I0216 03:23:55.368991    3772 main.go:1131]   [FAIL] status default output [It] prints addons
I0216 03:23:55.369170    3772 main.go:1131]   C:/k2s/test/e2e/cli/cmd/status/setuprequired/common/common.go:18
I0216 03:23:55.369170    3772 main.go:1131] 
I0216 03:23:55.369170    3772 main.go:1131] Ran 4 of 27 Specs in 6.074 seconds
I0216 03:23:55.369170    3772 main.go:1131] FAIL! -- 3 Passed | 1 Failed | 0 Pending | 23 Skipped
I0216 03:23:55.369170    3772 main.go:1131] --- FAIL: TestStatus (6.08s)
I0216 03:23:55.369170    3772 main.go:1131] FAIL

**Comment by krotz-dieter** [comment]
Also wsl test run failure has the same root cause

**Comment by mahenarayan** [comment]
Fixed by #178
