### ISSUE TITLE
Status for new worker nodes added by node cmd

### ISSUE THREAD

**Issue by krotz-dieter** [Siemens-Healthineers/K2s#191]
The issue #39 introduces the possibility to add and remove new nodes.
Within this issue the `status` cmd needs to be enhanced so that it supports these additional nodes.
In case of an `status` for the additional worker nodes the cmd shall show also the new added nodes.

**Comment by mahenarayan** [comment]
Already part of main. Hence, closing this.
![image](https://github.com/user-attachments/assets/d6a16649-9169-403b-a01a-1bb025deca10)
