### ISSUE TITLE
Image export does not work with name for windows container

### ISSUE THREAD

**Issue by krotz-dieter** [Siemens-Healthineers/K2s#214]
**Describe the bug**
Image export does not work with name for windows container

Enable smb-share addon

Try to export smb-share addon image:
shsk2s.azurecr.io/kubernetes-sigs/sig-windows/csi-proxy

k2s.exe image export -n "shsk2s.azurecr.io/kubernetes-sigs/sig-windows/csi-proxy" -t "1.tar" -o

will fail with message:

Image shsk2s.azurecr.io/kubernetes-sigs/sig-windows/csi-proxy not found!

**Comment by achimkist** [comment]
image name has to include tag:

```k2s.exe image export -n "shsk2s.azurecr.io/kubernetes-sigs/sig-windows/csi-proxy:v1.1.2" -t "1.tar" -o```

can be improved in help output.

Nevertheless still fails with following error:

```
Exporting image shsk2s.azurecr.io/kubernetes-sigs/sig-windows/csi-proxy:v1.1.2. This can take some time...
⏳ time="2024-02-26T13:04:42+01:00" level=fatal msg="content digest sha256:f68fe0105955a4b629085122da4e24981a4f4cd85d71f3fa8b188c8374a38a13: not found"
E0226 13:04:42.320081   18076 psexecutor.go:204] time="2024-02-26T13:04:42+01:00" level=fatal msg="content digest sha256:f68fe0105955a4b629085122da4e24981a4f4cd85d71f3fa8b188c8374a38a13: not found"
```

**Comment by achimkist** [comment]
Solution discussed with @mahenarayan: 

Before saving windows images with nerdctl, pull all layers of the image for all platforms.
There is a restriction in offline mode, in that case only the coressponding layers for the specific windows image version is exported. User will be informed in help output and during export

Import will only imported needed windows image version.
