### ISSUE TITLE
Main documentation structure using readthedocs

### ISSUE THREAD

**Issue by krotz-dieter** [Siemens-Healthineers/K2s#234]
Restructure the documentation in a similar way like for example the argo workflows documentation is done:
https://argo-workflows.readthedocs.io/en/latest/

Provide chapters like: Getting started, User guide, Operator manual, Developer guide ....

**Comment by jgriegershs** [comment]
- Markdown documentation is re-structured
- HTML documentation is generated and hosted on GitHub Pages: https://siemens-healthineers.github.io/K2s/
- HTML documentation adaptions for v1.0.0 are pushed to this branch: https://github.com/Siemens-Healthineers/K2s/tree/234-create-100-docs
