### ISSUE TITLE
Start/stop K2s using another user account

### ISSUE THREAD

**Issue by gabriel-rosso** [Siemens-Healthineers/K2s#24]
The cluster start/stop from a user account that differs from the user account used on cluster installation fails because of missing config files.

_Possible solution:_
Add an option to the CLI to copy the needed config files.

**Comment by mahenarayan** [comment]
Follow the discussion here https://github.com/Siemens-Healthineers/K2s/discussions/26

**Comment by jgriegershs** [comment]
According to #26 , the solution shall be:
- first step/increment is to grant the same access rights the installing user has to the new user account in question, fine-grained permissions are out of scope for now -> create new command, e.g. `k2s system user add`, `k2s system user ls` and `k2s system user rm`
- `.kube` folder must be re-created for additional users, containing their K8s auth certs
- `.ssh` folder must be re-created for additional users, containing their SSH auth key
- `setup.json` file must be moved to a system-central location, write access only granted to the installing user and read access for all others
- `.docker` folder containing credentials for access of `shsk2s.azurecr.io` registry -> usage of `config.json` file must be analyzed; ideally this file can be removed and the *Docker* daemon be configured in a different way

**Comment by jgriegershs** [comment]
Documentation is available at https://siemens-healthineers.github.io/K2s/next/op-manual/adding-k2s-users/.

Additional refactoring & testing is covered by #672.
