### ISSUE TITLE
Copy-FromToMaster fails on certain directories

### ISSUE THREAD

**Issue by krotz-dieter** [Siemens-Healthineers/K2s#343]
**Describe the bug**
Copy-FromToMaster fails on certain directories. This failure is coming from the fact that scp.exe is not working correctly when using -r flag.

**To Reproduce**
1. Copy folder [controller](https://github.com/linkerd/linkerd2/tree/main/controller) to a place on your disk (like `c:\x`)
2. Execute the internal command: 
`scp.exe -o StrictHostKeyChecking=no -r -v -i "C:\Users\YOURUSER\.ssh\kubemaster\id_rsa" c:\x\controller remote@172.19.1.100:tmp/`
3. You will observe that scp did not copy all of the subfolders in the remote VM

**Expected behavior**
All subfolders are copied to target directory in VM

**Additional context**
Adding this code part:
```
       # check if the source is a directory
        if (Test-Path -Path $Source -PathType Container) {
            # get last item in path from source
            $DirectoryAtTheEnd = Split-Path -Leaf $Source
            # get directory path from target after last :
            $TargetDirectory = $Target -replace '.*:', ''
            # make directory in master VM  
            ExecCmdMaster "mkdir -p $TargetDirectory/$DirectoryAtTheEnd"
            # extend source with all files
            $Source = $Source + '\*'
            # extend target with directory
            $Target = $Target + '/' + $DirectoryAtTheEnd
            Write-Log "copy directory: $Source to: $Target"
        }
        scp.exe -o StrictHostKeyChecking=no -r -i $global:LinuxVMKey "$Source" "$Target" 2>&1 | ForEach-Object { "$_" }
```
in method `Copy-FromToMaster` solves the problem in image build use case, but a more general solution (recursive path creation) needs to be implemented.

**Comment by achim92** [comment]
https://github.com/Siemens-Healthineers/K2s/blob/6ee9580c1ed6e7f5fb625d8612a98987ac6ca1f3/addons/gpu-node/Enable.ps1#L141C1-L144C91

**Comment by achimkist** [comment]
scp fix for Windows worker VM missing
