### ISSUE TITLE
Command system: Eliminate the double powershell code parts

### ISSUE THREAD

**Issue by krotz-dieter** [Siemens-Healthineers/K2s#352]
#265 Child of [Eliminate the double powershell code parts...](https://github.com/Siemens-Healthineers/K2s/issues/265)

Functionality: `k2s system ...` k2s system command

Eliminate double code parts in high level scripts used
Move those functionalities under the PowerShell modules and scripts -> [lib](https://github.com/Siemens-Healthineers/K2s/tree/main/lib)

Steps:
- use a branch, keep the branches for the issue as short living as possible (often merges to main)
- keep for start the high level scripts which are called from k2s cli directly
- in each high level script sync first the functionality within separate modules from [lib](https://github.com/Siemens-Healthineers/K2s/tree/main/lib)
- delete afterwards the functionality from the high level scripts, eliminate with this the double code
- remove the common global variables and global functions parts from the high level scripts
- use at the end high level scripts from [scripts](https://github.com/Siemens-Healthineers/K2s/tree/main/lib/scripts) which are using exclusively lib [modules](https://github.com/Siemens-Healthineers/K2s/tree/main/lib/modules)

**Comment by jgriegershs** [comment]
`k2s system upgrade` already migrated with https://github.com/Siemens-Healthineers/K2s/commit/b2c30905da876481691584acdcfdd2f3ec39d0c4.
