### ISSUE TITLE
Can't create a Windows image

### ISSUE THREAD

**Issue by gabriel-rosso** [Siemens-Healthineers/K2s#376]
I want to create a Windows image that contains a **simple .NET 4.8 application**. 
After searching on the internet I've found a tutorial with a sample application (https://github.com/microsoft/dotnet-framework-docker/tree/main/samples/dotnetapp), which I've downloaded to "C:\temp\dotnetapp". The base image specified in the Dockerfile is _mcr.microsoft.com/dotnet/framework/sdk:4.8_

When running `k2s image build -f c:\temp\dotnetapp\Dockerfile -d . -n mydotnet -t v1 -o -w` to create the image I get the following exception:

![Windows image creation](https://github.com/Siemens-Healthineers/K2s/assets/154501955/35d6dcf1-e325-4383-8b99-857451d66b19)

My **Windows host** has the following version (obtained by running "winver" from the command shell): **Version 22H2** (OS Build 19045.4170)

**Comment by krotz-dieter** [comment]
This is normal since the sdk:4.8 has no base for 22H2. In predev registry there is already a base for dotnet framework and 22H2.

**Comment by gabriel-rosso** [comment]
When inspecting the image _mcr.microsoft.com/dotnet/framework/sdk:4.8_ by issuing the command `docker manifest inspect mcr.microsoft.com/dotnet/framework/sdk:4.8` I've found that the image can only be used for the following Windows OS versions (see https://github.com/Siemens-Healthineers/K2s/blob/main/README.md):
- "10.0.14393.6897" (Windows 10, Version 1607)
- "10.0.17763.5696" (Windows 10, Server 2019, Version 1809)
- "10.0.20348.2402" (Windows Server 2022, Version 21H2)

None of them matches the version of the mentioned Windows host (Windows 10, Version 22H2).
Since there must be a kernel compatibility between the Windows host and the Windows container that will running on it, the appropriate base image must be used.

A list of available versions of .NET images is given in _https://mcr.microsoft.com/v2/dotnet/framework/sdk/tags/list_
For **Windows 10 Version 22H2** the tag **4.8-windowsservercore-20H2** has to be used, since Microsoft does not provide a specific image for the Windows 10 Version 21H2 and 22H2 but made the 20H2 image usable in Windows 10 Version 21H2 and 22H2.

### Solution: 
Adapt the Dockerfile to use the base image _mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-20H2_
