### ISSUE TITLE
system upgrade: only minor version upgrades allowed

### ISSUE THREAD

**Issue by jgriegershs** [Siemens-Healthineers/K2s#439]
### Problem
The current implementation of `k2s system upgrade` only allows minor version upgrades with version number increase restriction of *1*:
- `1.0.0 -> 1.1.0` -> **allowed** (minor increase of *1*)
- `1.0.0 -> 1.2.0` -> **not allowed** (minor increase of *2*)
- `1.0.0 -> 1.0.1` -> **not allowed** (patch increase of *1*)
- `1.0.0 -> 2.0.0` -> **not allowed** (major increase of *1*)

### Solution
Allow the following upgrades:
**TO BE DEFINED**

**Comment by krotz-dieter** [comment]
The solution from my eyes shall be:

1.0.0 -> 1.1.x -> allowed (minor increase of 1)
1.0.0 -> 1.2.x -> not allowed (minor increase of 2)
1.0.0 -> 1.0.x -> allowed (patch increase of 1)
1.0.0 -> 2.x.x -> not allowed (major increase of 1)
1.9.x -> 2.0.x -> allowed (major increase from last minor release)

**Comment by jgriegershs** [comment]
`system upgrade` has errors (see #484).
