### ISSUE TITLE
[addons] smb-share error when restarting machine

### ISSUE THREAD

**Issue by krotz-dieter** [Siemens-Healthineers/K2s#481]
**Describe the bug**
After restart of host machine in some cases the smb-share addon does not run anymore correctly, specially the windows container of the smb-addon will not be able to start.

**To Reproduce**
- start a k2s cluster on your machine
- reboot
- start the cluster again after reboot
- k2s status to see the corrupted state

**Expected behavior**
Expected behavior is that the smb-share addon works after the k2s start after the reboot

It turned out that after reboot if you delete the hns networks and then do a fresh start the problem is solved.
It has to be analyzed why the hns network get's corrupted in this case.

**Comment by mahenarayan** [comment]
Unable to reproduce the issue with mentioned steps. Tried 10 times by restarting machine and starting the cluster but smb-share windows pods recovers normally without any issue.
