### ISSUE TITLE
Failed to join jetson worker into k2s cluster

### ISSUE THREAD

**Issue by yanrunming** [Siemens-Healthineers/K2s#488]
I want to join a NVIDIA Jetson worker into k2s cluster. But when I joined it into k2s cluster, the worker node's status was NotReady.

** My Environment **
1. Win10 host(192.168.33.231) and a NVIDIA Jetson worker (192.168.33.16) in the same intranet that can access internet.
2. K2s cluster in win10 host is installed successfully, and 'k2s status' gets the result successfully. 
3. K2s master node's IP is 172.19.1.100
4. To enable win10 forwarding function by set IpEnableRouter=1 in 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters' and 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters'
5. Jetson adds a static route 'sudo ip route add 172.19.1.0/24 via 192.168.33.231'.
6. Jetson can ping 172.19.1.100 and access the apiserver(https://172.19.1.100:6443) successfully.
7. K2s master node can ping 192.168.33.16 OK.

**To Reproduce**
1. In Jetson, run "sudo kubeadm join 172.19.1.100:6443 --token 6a93od.q37jkik6bgkhrqn3 --discovery-token-ca-cert-hash sha256:90746da6c00f0162f7f5c3de444a3f43ef5c6cacf3c240cba198f1dbcefbab7c -v 5"
2. The result "This node has joined the cluster" seems OK.
3. In master node, run 'kubectl get nodes' and the result show jetson worker's status is "NotReady"
4. In jetson, run 'journalctl -u kubelet -b --no-pager' and get many errors like 【Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized"】

**Additional context**
For more detail logs, please see the accessories.
[0522-jetson-errors.txt](https://github.com/Siemens-Healthineers/K2s/files/15398381/0522-jetson-errors.txt)

[0522-master-logs.txt](https://github.com/Siemens-Healthineers/K2s/files/15398382/0522-master-logs.txt)

**Comment by mahenarayan** [comment]
Hi @yanrunming Thank you for trying out k2s. Looks like you are trying to add external machine as a node to an existing k2s cluster. This is not supported from us yet but in the pipeline. 
Now, coming to your error message node "NotReady", kubeadm join is one of the steps to initialize a machine as node. There are several steps such as setting up container runtime, setting up CNI which needs to be performed on Jetson worker which are missing in your setup.

**Comment by krotz-dieter** [comment]
Adding new nodes will be provided in future by the new node command [Issue #39](https://github.com/Siemens-Healthineers/K2s/issues/39) Till then, no additional nodes can be added to the cluster.
