### ISSUE TITLE
k2s.exe blocked by virus protection

### ISSUE THREAD

**Issue by yanrunming** [Siemens-Healthineers/K2s#496]
I have installed k2s v1.0.0 and its cluster. I want to upgrade to the latest version from main branch. And I pull the latest code and uninstall the current k2s cluster. On making an offline package by running 【k2s.exe system package -d c:\temp -n k2s_offline_package.zip --for-offline-installation】, I came into an error that k2s.exe blocked and deleted by virus protection. But on a machine that never install k2s, there is no warning.

![k2s-blocked-by-virus](https://github.com/Siemens-Healthineers/K2s/assets/165352181/d04661f9-ccba-42eb-b7d8-d43e50d90646)

**Comment by yanrunming** [comment]
![Screenshot 2024-05-24 122314](https://github.com/Siemens-Healthineers/K2s/assets/165352181/535a82fb-082e-4d87-b42c-995af405a67a)

**Comment by krotz-dieter** [comment]
Problem will be covered by issue: [53](https://github.com/Siemens-Healthineers/K2s/issues/53).

Till then only a manual workaround is there: [Windows Virus & thread protection ][](https://github.com/Siemens-Healthineers/K2s/blob/main/doc/K8s_Troubleshoot.md)

Please use the workaround described in the link provided till we have this issue solved.
