### ISSUE TITLE
Help user to recover from corrupted k2s installation

### ISSUE THREAD

**Issue by mahenarayan** [Siemens-Healthineers/K2s#506]
**Is your feature request related to a problem? Please describe.**
As a user, I have no clear instruction to recover corrupted k2s cluster. If I try to uninstall then there is a general message to correct the script directly which is not understandable. 
```
C:\Users\syadmin>C:\K2s-main\K2s-main\k2s.exe install
Errors occurred during K2s setup. K2s cluster is in corrupted state. Please uninstall and reinstall K2s cluster.

C: \Users\syadmin>C:\K2s-main\K2s-main\k2s.exe uninstall
# Uninstalling K2s v1.0.1+b55066d
could not determine the setup type, aborting. If you are sure you have a K2s setup installed, call the correct uninstall script directly
ime-2024-05-28T00:58:38.205+02:00 level-ERROR source-main.go:46 msg="error occurred during command execution" error="could not determine the setup type, aborting. If you are sure you have a K2s setup installed, call the correct uninstal
l script directly"

```

**Describe the solution you'd like**
A clean solution will be to handle corrupted state of k2s cluster. During uninstall, check the state of the cluster within CLI before calling script, if cluster is in corrupted state (this can be found in the entry of setup.json) then delete the setup.json and exit gracefully. Inform user to try installation again.

**Describe alternatives you've considered**
Inform user to delete the corrupted file `%USERPROFILE%\.kube\setup.json` and try installation again.

**Additional context**
![image](https://github.com/Siemens-Healthineers/K2s/assets/154434373/5c05c9fd-b2ce-4338-8e8e-65f23c0cf9be)

**Comment by krotz-dieter** [comment]
In case that something failed to provision the debian VM unfortunately nothing is cleanup during uninstall. Switches and intermediate VMs are remaining.

**Comment by krotz-dieter** [comment]
Also besides the provisioned VM als the bin/provisioning folder is kept and not deleted during uninstall.
