### ISSUE TITLE
Support using custom builds of kubernetes

### ISSUE THREAD

**Issue by jsturtevant** [Siemens-Healthineers/K2s#516]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use local build of Kubernetes for testing and start the cluster with the binaries build from source.

**Describe the solution you'd like**
Something like k2s.exe install --wsl --k8s-bins ./output/bins

**Describe alternatives you've considered**
Starting up the cluster, stoping kubelet, replacing the binary and restarting kubelet.

**Additional context**
This would make building and testing kubernetes locally on Windows machine in a fast iterative way.

**Comment by krotz-dieter** [comment]
Feature makes sense and we will consider it. In this way we can also test certain releases with binaries from a folder.
We will plan it for next release K2s 1.2.0. Currently we are working to finish the K2s 1.1.0.

**Comment by krotz-dieter** [comment]
Option --k8s-bins  should also be considered if creating offline package with `k2s system package --k8s-bins`.
In this way we can create k2s offline packages which include all components with custom K8s binaries.

**Comment by achimkist** [comment]
@jsturtevant `k2s.exe install --k8s-bins` option is on main now. You can place your Windows Kubernetes binaries (kubelet,.exe, kubeadm.exe, kube-proxy.exe, kubectl.exe) in that folder and they will be used when installing the cluster. Hope this works for you. Should this use case be supported for Linux as well?
