### ISSUE TITLE
How to start cluster with a specific kubernetes version?

### ISSUE THREAD

**Issue by jsturtevant** [Siemens-Healthineers/K2s#517]
**Describe the bug**

The current kubernetes version that gets installed is 1.25.3 which is no longer supported upstream. I can' find how to change that value via `k2s.exe install`.

**To Reproduce**

**Expected behavior**
Be able to install any supported version of k8s.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by krotz-dieter** [comment]
Currently on mainline we have now K8s 1.29.5, we will do the feature to install from a binary folder like described in issue: [#516](https://github.com/Siemens-Healthineers/K2s/issues/516). If that's OK, i will close this issue.

**Comment by krotz-dieter** [comment]
With issue #516 we will provide the option to specify a folder with the K8s binaries to be used. This issue is requesting the same feature.
