### ISSUE TITLE
[install] k2s install with linux-only does not support offline installation

### ISSUE THREAD

**Issue by mahenarayan** [Siemens-Healthineers/K2s#561]
**Describe the bug**
When offline package is used to install k2s linux-only, there is no offline installation as it defaults to online installation. 

**To Reproduce**
1. Obtain a offline package
2. `k2s install --linux-only`

**Expected behavior**
Offline install should be supported as the required components are present in offline package.

**Comment by krotz-dieter** [comment]
Should be resolved by the new node cmd and the fact that we would remove the option #63. Propose to close it.
