### ISSUE TITLE
[addons] smb-share installed in incorrect namespace

### ISSUE THREAD

**Issue by mahenarayan** [Siemens-Healthineers/K2s#579]
**Describe the bug**
`smb-share` addon is getting installed in kube-system namespace. Ideally it should be in different e.g storage namespace.
Found in version k2s 1.0.0

**To Reproduce**
1. `k2s addons enable smb-share`
2. `kubectl get pods -A`

**Expected behavior**
`smb-share` resources should be installed in a separate namespace e.g `k2s-storage` as kube-system is dedicated for core kubernetes resources.

**Screenshots**
![image](https://github.com/Siemens-Healthineers/K2s/assets/154434373/e7b36060-7a16-4d93-94f1-cb0cec36fd8a)

**Comment by achimkist** [comment]
related #334
