### ISSUE TITLE
[HNS] Windows Server 2019 (1809) HNS is not started automatically

### ISSUE THREAD

**Issue by mahenarayan** [Siemens-Healthineers/K2s#593]
**Describe the bug**
On a Windows Server 2019 (1809) machine, HNS (Host Network Service) is not started automatically after enabling [pre-requisites](https://github.com/Siemens-Healthineers/K2s/blob/main/docs/op-manual/installing-k2s.md#:~:text=All%20%2DNoRestart-,Windows%20Server%20OSs,-Enable%2DWindowsOptionalFeature%20%2D) Windows Container Features.

**To Reproduce**
1. Enable Windows Container Features on Windows Server 2019 (1809)
2. Reboot
3. Check HNS is still Manual state and not Running.

**Expected behavior**
HNS should be started after enabling Windows Container Features with a reboot.

**Additional context**
Can `k2s install` start HNS during installation provided the pre-requisites are met?

**Comment by krotz-dieter** [comment]
Tested on Server 2019 with version Microsoft Windows [Version 10.0.17763.3650]. HNS service is not started automatically, nevertheless k2s install works since we start HNS during install. Maybe the problem is related to the version of the server 2019 system.

**Comment by krotz-dieter** [comment]
Function Stop-InstallIfNoMandatoryServiceIsRunning has changed in latest to not test against running hns svc, please use latest packages. For v1.0.0 we will not change this anymore, for 1.0.0 user has to check that prerequisites are there and the svc running.
