### ISSUE TITLE
Windows container cannot be started

### ISSUE THREAD

**Issue by wtjwtjwtj** [Siemens-Healthineers/K2s#601]
**Describe the bug**
K2s 1.1.0 is offline installed on a computer which cannot access to internet.
Windows container image has been imported successfully into k2s, but the container cannot be started.
Following error is found in the output of "k describe pod":
Warning  FailedCreatePodSandBox  3s (x23 over 9m6s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "shsk2s.azurecr.io/pause-win:v1.0.0": failed to pull image "shsk2s.azurecr.io/pause-win:v1.0.0": failed to pull and unpack image "shsk2s.azurecr.io/pause-win:v1.0.0": failed to resolve reference "shsk2s.azurecr.io/pause-win:v1.0.0": failed to do request: Head "https://shsk2s.azurecr.io/v2/pause-win/manifests/v1.0.0": dial tcp: lookup shsk2s.azurecr.io: no such host

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2, OS Build 19044.4412

**Additional context**
It works with K2s 1.0.0 before.

**Comment by mahenarayan** [comment]
@wtjwtjwtj Thank you for raising the issue, can you share the `k2s.log` file under `c:\var\log` to investigate further.

**Comment by wtjwtjwtj** [comment]
[k2s.zip](https://github.com/user-attachments/files/15952678/k2s.zip)
Thanks for the reply. @mahenarayan 
The k2s.log is attached.

**Comment by wtjwtjwtj** [comment]
Sure. 🙂
The dump zip file is attached.
[k2s-dump-VB20MS9WTJ-20240625T082359639.zip](https://github.com/user-attachments/files/15962743/k2s-dump-VB20MS9WTJ-20240625T082359639.zip)

**Comment by krotz-dieter** [comment]
We will provide the version 1.1.1 which will fix this issue, this has now highest prio for us.

**Comment by wtjwtjwtj** [comment]
@mahenarayan Thanks very much. With the workaround, the issue is solved.
@krotz-dieter Thanks for the information. It's not urgent for me as the workaround works for me. 

Not sure if it is related, regarding the "Unable to Run Windows Container on a Hardened Machine (AppLocker Rules)" in the known-issues(https://github.com/Siemens-Healthineers/K2s/blob/main/docs/troubleshooting/known-issues.md), I find the workaround is not quite correct. The Windows containers Pod can be started on a hardened computer after a new rule (to allow running C:\PAUSE.exe) is added. I get this hint from the Windows eventlog of AppLocker. But I don't know where C:\PAUSE comes from, is it from the image pause-win:v1.0.0?
![image](https://github.com/Siemens-Healthineers/K2s/assets/6497395/55164f81-e0c0-490c-87e3-864192a443bb)

**Comment by mahenarayan** [comment]
@wtjwtjwtj Good to know that it worked. Regarding, hardened machine, you are right adding new rule for each executable will ensure it is unblocked. `C:\PAUSE.exe` indeed comes from image pause-win:v1.0.0.  

Workaround clearly mentions that this is just a suggestion to unblock all executables but the actual solution is to create appropriate AppLocker rules after reviewing with security experts. We have observed AppLocker blocking `C:\Windows\System32\CMD.exe` as well, so just adding rule for PAUSE.exe will not work out for all cases.

**Comment by wtjwtjwtj** [comment]
@mahenarayan Thank you very much for the help and the clarification. I close this issue.

**Comment by riyapatel-ms** [comment]
Hi there, I am running k2s 1.1.1 but am still getting this error when attempting to apply my deployment YAML. When I navigate to the WindowsNodeArtifacts.zip\images I only see "TheImageCouldNotBePulled.txt". Would you be able to upload the tar file here?

**Comment by mahenarayan** [comment]
Hi @riyapatel-ms Could you share the `k2s.log` file under c:\var\log\ to investigate further?

**Comment by riyapatel-ms** [comment]
@mahenarayan [k2s.log](https://github.com/user-attachments/files/16540201/k2s.log)

**Comment by mahenarayan** [comment]
@riyapatel-ms Could you share the output of this command? `k2s image ls -A`
I see that there is an issue in pulling image from our public registry `shsk2s.azurecr.io`. Strangely, pulling image from `registry.k8s.io` and `docker.io` works. Perhaps the machine is behind some proxy or firewall which blocks unknown domain? Could you elaborate your setup? Is the machine behind proxy or some private network?

Error from the containerd log:
```
&PodSandboxMetadata{Name:hello-world-5f7d47bf57-sq25k,Uid:ae03ce58-f772-4658-9d80-4390d559c734,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox image \"shsk2s.azurecr.io/pause-win:v1.0.0\": failed to pull image \"shsk2s.azurecr.io/pause-win:v1.0.0\": failed to pull and unpack image \"shsk2s.azurecr.io/pause-win:v1.0.0\": failed to resolve reference \"shsk2s.azurecr.io/pause-win:v1.0.0\": failed to do request: Head \"https://shsk2s.azurecr.io/v2/pause-win/manifests/v1.0.0\": net/http: TLS handshake timeout"
time="2024-08-08T01:36:03.394457800-07:00" level=info msg="stop pulling image shsk2s.azurecr.io/pause-win:v1.0.0: active requests=0, bytes read=0"
```

**Comment by riyapatel-ms** [comment]
I changed locations and on the new network I did not run into the same error and am able to pull the pause image and it also shows in when i run "k2s image ls", will let you know if I run into this again or if it was just my network
![image](https://github.com/user-attachments/assets/3d2997ab-105c-4158-acd1-4f4a91d865f7)

**Comment by mahenarayan** [comment]
Normally, when you switch between networks or reboot machine it is recommended to restart the cluster.
```
k2s stop
k2s start
```
