### ISSUE TITLE
Error is produced whenever k2s is started

### ISSUE THREAD

**Issue by abhitoshj** [Siemens-Healthineers/K2s#667]
**Describe the bug**
Whenever start of k2s is performed, the following error is logged in the console. 

![image](https://github.com/user-attachments/assets/52dad095-a5d1-4deb-8471-a89db7fd7a12)

![image](https://github.com/user-attachments/assets/2eb1e9d5-9c7b-41a7-afa5-4769d23a311d)

**To Reproduce**
- start K2s using command ***k2s start -o***

**Expected behavior**
No errors are produced during k2s start

**Comment by krotz-dieter** [comment]
The issues is not comming up anymore, will close it.
