### ISSUE TITLE
Logging addon dashboard not reachable anymore via port forwarding

### ISSUE THREAD

**Issue by achimkist** [Siemens-Healthineers/K2s#704]
**Describe the bug**
Logging addon dashboard not reachable anymore via port forwarding

**To Reproduce**
1. Enable logging addon
2. kubectl -n logging port-forward svc/opensearch-dashboards 5601:5601
3. Open http://localhost:5601
4. {"statusCode":404,"error":"Not Found","message":"Not Found"}

**Expected behavior**
Dashboard should be accessible

**Additional context**
No rewrite rule supported for port forwarding 
https://github.com/Siemens-Healthineers/K2s/blob/main/addons/logging/manifests/opensearch-dashboards/deployment.yaml#L76-L79

**Comment by achimkist** [comment]
@krotz-dieter @mahenarayan What is your opinion on this? Shall we remove port-forwarding and enable ingress nginx or ingress traefik automatically upfront if not already done yet when enabling the logging addon?

**Comment by krotz-dieter** [comment]
For the addons if one ingress or gateway implemention is on, then we shall use that. Port forwarding only maybe in docu as fallback.
