### ISSUE TITLE
Timely centralized logging?

### ISSUE THREAD

**Issue by yanrunming** [Siemens-Healthineers/K2s#706]
Is there some functions like fluentd in k2s? I notice some logs could timely be written to c:/var/log.
How to timely centralize the logs of my workloads (my customized applications and 3rd-party applications) and save them to some folder like c:/var/log on host ?
E.g. I ran a Redis pod on nvidia Jetson worker. Any best practice for outputting its logs to c:/var/log/pods/redis-xxx on host.

Thanks!

**Comment by mahenarayan** [comment]
@achimkist I believe this can be achieved with our logging addon, could you help @yanrunming?

**Comment by achimkist** [comment]
@yanrunming for centralized logging we provide the `logging` addon which uses fluentbit and opensearch (dashboards). Or you can just inspect your Linux logs inside the KubeMaster VM using `k2s system ssh m`.

**Comment by yanrunming** [comment]
Thanks
