### ISSUE TITLE
Cannot list images where registry addon is enabled.

### ISSUE THREAD

**Issue by abhitoshj** [Siemens-Healthineers/K2s#754]
The registry addon was enabled using the following command:
_k2s addons enable registry --ingress traefik --default-credentials_

An image was built using _k2s image build --push_

The image was available in the k2s registry. 

However, when listing the image using _k2s image ls_, the following excaption was encountered:
![image](https://github.com/user-attachments/assets/ea18f44f-a76c-48ea-9a74-9a6177f08a85)

Version information:
k2s: v1.1.2+fba0467
  BuildDate: 2024-09-10T11:31:04Z
  GitCommit: fba046773fb8f8ba1f98a9bb7bc30bc71e5661f5
  GitTreeState: clean
  GoVersion: go1.22.3 X:boringcrypto
  Compiler: gc
  Platform: windows/amd64

**Comment by abhitoshj** [comment]
Fix submitted on release-1.1.x

**Comment by krotz-dieter** [comment]
Also a test case would be needed here to avoid this in future.
