### ISSUE TITLE
Please update flannel version

### ISSUE THREAD

**Issue by Najzer0** [Siemens-Healthineers/K2s#767]
Imported version to kube-flannel.yml holds references to
        image: rancher/mirrored-flannelcni-flannel-cni-plugin:v1.1.0 
and
        image: rancher/mirrored-flannelcni-flannel:v0.18.1

that use an outdated alpine-linux with vulns included.

Please bump flannel to a higher version: eg. 0.25.6

**Comment by krotz-dieter** [comment]
Updated to latest 0.26.1
