### ISSUE TITLE
Linux-only installation fails in v1.1.2

### ISSUE THREAD

**Issue by gabriel-rosso** [Siemens-Healthineers/K2s#795]
The linux-only installation was aborted with the following message stack:
 
powershell { C:\k2s_v1.1.2\k2s.exe install --linux-only --master-memory 2GB -o }
🤖 Installing K2s 'multivm' v1.1.2+fba0467 in 'C:\k2s_v1.1.2' on Microsoft Windows 10 Enterprise 10.0.19045.4894 Build 19045.4894 using PowerShell 5
⏳ [11:44:06] ---------------------------------------------------------------
⏳ [11:44:06] Multi-VM Kubernetes Installation started.
⏳ [11:44:06] ---------------------------------------------------------------
⏳ [11:44:06] Offline installation is currently not supported for 'multi-vm', falling back to online installation.
⏳ [11:44:06] Multi-VM setup will install Linux node only
⏳ [11:44:06] Added C:\k2s_v1.1.2 to PATH variable
⏳ [11:44:06] Added C:\k2s_v1.1.2\bin to PATH variable
⏳ [11:44:06] Added C:\k2s_v1.1.2\bin\exe to PATH variable
⏳ [11:44:06] Added C:\k2s_v1.1.2\bin\docker to PATH variable
⏳ [11:44:06] Added C:\k2s_v1.1.2\bin\containerd to PATH variable
⏳ [11:44:06] Determining if proxy is configured by the user in Windows Proxy settings.
⏳ [11:44:06] No proxy configured in Windows Proxy Settings.
⏳ Write-Log : [11:44:07] C:\k2s_v1.1.2\smallsetup\multivm\Install_MultiVMK8sSetup.ps1 : The term '**Add-K2sHostsToNoProxyEnvVar**' _is not recognized as the name of a cmdlet,_
⏳ _function, script file, or   operable program._ Check the spelling of the name, or if a path was included, verify that the path is correct and try again.  At line:1 char:1
⏳ + &'C:\k2s_v1.1.2\smallsetup\multivm\Install_MultiVMK8sSetup.ps1' -Mast ...  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      + CategoryInfo
⏳        : ObjectNotFound: (Add-K2sHostsToNoProxyEnvVar:String) [Install_MultiVMK8sSetup.ps1], CommandNotFoundException      + FullyQualifiedErrorId :                               ⏳ CommandNotFoundException,Install_MultiVMK8sSetup.ps1                                                                                                                               ⏳ At C:\k2s_v1.1.2\lib\scripts\k2s\base\Invoke-ExecScript.ps1:46 char:13                                                                                                             ⏳ +             Write-Log $($_ | Out-String) -Error                                                                                                                                  ⏳ +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                  ⏳     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
⏳     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log
⏳
⏳ [11:44:07] Installation failed!

**Comment by gabriel-rosso** [comment]
After analysis the root cause is the wrong module "proxy.module.psm1" being imported.
 
In the file _".\smallsetup\multivm\Install_MultiVMK8sSetup.ps1"_ the module
_"$PSScriptRoot/../ps-modules/proxy/proxy.module.psm1"_ is imported
but it should be the module
_"$PSScriptRoot/../../lib/modules/k2s/k2s.node.module/windowsnode/proxy/proxy.module.psm1"_
 
The same applies for the file _".\smallsetup\common\InstallBuildOnlySetup.ps1"_

**Comment by abhitoshj** [comment]
Added [PR](https://github.com/Siemens-Healthineers/K2s/pull/818) towards the fix
