### ISSUE TITLE
Uninstallation cannot be performed if installation fails at a very early stage

### ISSUE THREAD

**Issue by gabriel-rosso** [Siemens-Healthineers/K2s#796]
When the installation fails at a very early stage (like in the case reported with the issue https://github.com/Siemens-Healthineers/K2s/issues/795) an uninstallation cannot be performed. 

Related to the issue mentioned above the error reported when triggering the uninstallation was: 

 powershell { C:\k2s_v1.1.2\k2s.exe uninstall -o }
🤖 Uninstalling K2s v1.1.2+fba0467
  ERROR   critical error occurred during command execution, aborting: could not determine the setup type, aborting. If you are sure you have a K2s setup installed, call the correct uninstall script directly
time=2024-10-09T12:14:13.134+02:00 level=ERROR source=main.go:80 msg="critical error occurred during command execution, aborting" error="**could not determine the setup type**, aborting. If you are sure you have a K2s setup installed, call the correct uninstall script directly" stack="goroutine 1 [running]:\nruntime/debug.Stack()\n\tC:/hostedtoolcache/windows/go/1.22.3/x64/src/runtime/debug/stack.go:24 +0x5e\nmain.handleUnexpectedError({0xf6e0e0, 0xc0002cd6c0})\n\tD:/a/K2s/K2s/k2s/cmd/k2s/main.go:80 +0xbc\nmain.main()\n\tD:/a/K2s/K2s/k2s/cmd/k2s/main.go:53 +0x465\n"

Proposed solutions:
- persist the setup type as early as possible in the installation phase in order to make an uninstallation possible.
- offer a cli option to perform a deep clean up regardless of the installation type.

**Comment by mahenarayan** [comment]
Solution already exists in mainline, refer #506
