### ISSUE TITLE
feat(ci): Setup K2s Continuous Integration Pipeline 

### ISSUE THREAD

**Issue by mahenarayan** [Siemens-Healthineers/K2s#8]
- [x] Pipeline for running unit tests
- [x] Pipeline for building k2s cli.
- [x] Pipeline for building k2s artifacts including [bridge.exe, cloudinitisobuilder.exe, devgon.exe, httpproxy.exe, k2s.exe, vfprules.exe, yaml2json.exe, zap.exe] 
- [x] Caching of go modules @abhitoshj

**Comment by abhitoshj** [comment]
When the features branches or pull requests have caches that are not used for more than 7 days, then they are deleted by Github. Please check [Cache Eviction Policy](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy)

If we see that the utilization is still going beyond 10GB with action caches from multiple branches and PR, then a cron-workflow could be developed to handle this.
