### ISSUE TITLE
New addon for k2s which deals with logging

### ISSUE THREAD

**Issue by krotz-dieter** [Siemens-Healthineers/K2s#86]
**Is your feature request related to a problem? Please describe.**
Many users need a way to search for logs which are produced inside the K8s cluster.
The logs are needed in order to analyze errors and different behaviors in the cluster,
in the logging addon also a web UI shall be integrated which allows an easy search in all the logs
produced by the K8s entities (nodes, K8s components, ...) and the K8s workflows from all of the namespaces. 

**Describe the solution you'd like**
A solution based on fluentd would be great, since fluentd seems to be very popular and stable at the CNCF.
But maybe other projects could also fit in here.

**Additional context**
With this issue it should be analyzed besides fluentd which other open source project would fit best for such an logging addon.

**Comment by achimkist** [comment]
First approach:

- use Fluentbit as log collector, for windows nodes create host process container, for Linux create manifest files from helm charts
- running as Daemonsets on Windows and Linux nodes
- use Opensearch as database and Opensearch Dashboards for visualization (fork of elasticsearch and kibana when it still was under Apache 2.0 license)

**Comment by achimkist** [comment]
support for linux only and multi-vm missing

**Comment by achimkist** [comment]
Remove old solution in monitoring addon: Vali and Valitail (not needed anymore since fluent, opensearch and plutono integration of opensearch)

**Comment by achimkist** [comment]
Add support for OpenTelemetry
