### ISSUE TITLE
Failed to access internet in pod on hyper-v vm node

### ISSUE THREAD

**Issue by yanrunming** [Siemens-Healthineers/K2s#876]
I want to deploy a TCP/UDP client in win10 node. I have three nodes in k2s cluster(v1.1.1): master, win10 worker(172.20.1.2), Jetson worker. And the master and the win10 worker are in hyper-v. I can't access the external network in pods on win10 worker. At the same time, pods on jetson worker could.
```
# in pod (172.20.1.3) on win10 node, failed to access www.bing.com or its IP
curl www.bing.com  

# in pod on jetson node, failed to access www.bing.com by domain name, but could access its IP
curl www.bing.com 
curl: (6) could not resolve host: www.bing.com

curl 202.89.233.100 # could get its responses
```

I notice httpproxy's parameter contains "--allow-cidr 172.20.0.0/16" and according to [httpproxy doc](https://siemens-healthineers.github.io/K2s/latest/op-manual/configuring-httpproxy-service/) win10 node vm should have internet access.

![win-node-internet-access](https://github.com/user-attachments/assets/02180ff1-167c-41a8-8f6f-3d13d2dd32fb)

**Comment by krotz-dieter** [comment]
Please use -x http://172.19.1.1:8181 for curl.

**Comment by yanrunming** [comment]
Thanks, dieter!
Could httpproxy support general TCP/UDP traffic? 
I plan to deploy a DICOM node in win pod, and it includes a tcp server and a tcp client.

**Comment by yanrunming** [comment]
Hi, dieter. 
I am not sure if I made myself clear. My program is a tcp/udp client and runs in pod of the win worker node. Could the ingress-nginx act as a tcp/udp proxy, similar with http-proxy supporting pods access the external server? 
In this case, I didn't mean to expose the server in pods.
Thanks for your patience!
![k2s-outbound-traffic](https://github.com/user-attachments/assets/914e1902-ee05-48fb-aedc-fd822a1bfd81)

**Comment by krotz-dieter** [comment]
Is your machine in an network where you have a proxy ? Do you have NAT enabled for your VM ? There could be multiple reasons why the connection cannot work, please invite for next week for a meeting where we can look for the reason of failure.

**Comment by yanrunming** [comment]
Pod could access the external service on the host PC via IP or DNS.
![k2s-external-service](https://github.com/user-attachments/assets/343d40f7-89e7-4b09-bef4-e5f6198b19ed)

Thanks for your kindness!
