### ISSUE TITLE
DNS changes on network interface can lead to network failure

### ISSUE THREAD

**Issue by achimkist** [Siemens-Healthineers/K2s#902]
**Describe the bug**
During the installation the primary DNS entry of the physical network adapter is changed to `172.19.1.1`. The originally DNS servers are moved to the local DNS server (dnsmasq) on the KubeMaster VM. In some cases it happens sporadically that the pyhsical network adapter is not observered as "up" during cluster stop. Therefore the DNS server can't be resetted and the system looses network connectivity.

**To Reproduce**
1. Install the cluster
2. Stop and start the cluster several times

**Expected behavior**
DNS resolution is stable and the DNS servers on the physical network adapter are always resetted during stop and uninstallation

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version 21H2

**Additional context**
https://github.com/Siemens-Healthineers/K2s/blob/2b8a1c2d269b13a46d499f429d39438127df07b9/lib/modules/k2s/k2s.infra.module/network/windows-host-network.module.psm1#L61

**Comment by mahenarayan** [comment]
@achimkist  Thanks for reporting this, probably relying on 'Up' status is not working out here. Storing the physical interface information might help, Is the interface always in 'down' state or briefly during start/stop, because a retry might help as well.
